-- BrainQueue · telemetry event log + focus sessions.
-- Run in the Supabase SQL editor (or `supabase db push`). Idempotent.
--
-- task_events is the "moat": an append-only record of what the user does with
-- tasks. It is immutable by design — RLS allows only insert + select of your own
-- rows (no update/delete policy), so even the owner can't rewrite history.

-- 1. Append-only event log -----------------------------------------------------
create table if not exists public.task_events (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  task_id    text,                       -- null for session-level events
  event_type text not null,
  event_at   timestamptz not null default now(),
  context    jsonb,
  created_at timestamptz not null default now()
);
create index if not exists task_events_user_time_idx on public.task_events (user_id, event_at desc);

alter table public.task_events enable row level security;
drop policy if exists "task_events_insert_own" on public.task_events;
create policy "task_events_insert_own" on public.task_events
  for insert with check (auth.uid() = user_id);
drop policy if exists "task_events_select_own" on public.task_events;
create policy "task_events_select_own" on public.task_events
  for select using (auth.uid() = user_id);
-- (deliberately no update/delete policy → rows are immutable)

-- 2. Focus sessions ------------------------------------------------------------
create table if not exists public.sessions (
  id                 bigint generated by default as identity primary key,
  user_id            uuid not null references auth.users(id) on delete cascade,
  started_at         timestamptz not null default now(),
  ended_at           timestamptz,
  planned_task_ids   text[] not null default '{}',
  completed_task_ids text[] not null default '{}',
  focus_seconds      integer not null default 0,
  created_at         timestamptz not null default now()
);
create index if not exists sessions_user_time_idx on public.sessions (user_id, started_at desc);

alter table public.sessions enable row level security;
drop policy if exists "sessions_select_own" on public.sessions;
create policy "sessions_select_own" on public.sessions for select using (auth.uid() = user_id);
drop policy if exists "sessions_insert_own" on public.sessions;
create policy "sessions_insert_own" on public.sessions for insert with check (auth.uid() = user_id);
drop policy if exists "sessions_update_own" on public.sessions;
create policy "sessions_update_own" on public.sessions for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
